### ISSUE TITLE
ReferenceError: URL is not defined

### ISSUE THREAD

**Issue by floofla** [kozlovzxc/archer#1]
./archer.js -u http://example.com

ReferenceError: URL is not defined
    at Object.generate (/home/mars/archer/scanners/xss.js:15:21)
    at fs.readdirSync.forEach.file (/home/mars/archer/archer.js:28:28)
    at Array.forEach (<anonymous>)
    at main (/home/mars/archer/archer.js:26:6)
    at Object.<anonymous> (/home/mars/archer/archer.js:40:1)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)

    at Function.Module._load (module.js:495:3)

Chrome is already installed, npm installed with no issues.

![zzz](https://user-images.githubusercontent.com/39817518/40818892-53ae457e-650e-11e8-99b3-25d99aceb484.png)

**Comment by skvoter** [comment]
@floofla Try update node to the latest version

**Comment by floofla** [comment]
Curious, which node version are you using?

**Comment by floofla** [comment]
Actually, fixed now. Thanks!
